using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Rage;
using System.Runtime.InteropServices;

namespace ScriptManager.Resources
{
    public static class Zones
    {
        public static string GetZoneName(Vector3 pos)
        {
            string zoneName = string.Empty;
            Vector3 Position = Game.LocalPlayer.Character.Position;
            unsafe
            {
                IntPtr ptr = Rage.Native.NativeFunction.CallByName<IntPtr>(
                    "GET_NAME_OF_ZONE",
                    Position.X, Position.Y, Position.Z);

                zoneName = Marshal.PtrToStringAnsi(ptr);
            }
            return zoneName;
        }

        public enum EZones
        {
            AIRP,
            ALAMO,
            ALTA,
            ARMYB,
            BANHAMC,
            BANNING,
            BEACH,
            BHAMCA,
            BRADP,
            BRADT,
            BURTON,
            CALAFB,
            CANNY,
            CCREAK,
            CHAMH,
            CHIL,
            CHU,
            CMSW,
            CYPRE,
            DAVIS,
            DELBE,
            DELPE,
            DELSOL,
            DESRT,
            DOWNT,
            DTVINE,
            EAST_V,
            EBURO,
            ELGORL,
            ELYSIAN,
            GALFISH,
            GOLF,
            GRAPES,
            GREATC,
            HARMO,
            HAWICK,
            HORS,
            HUMLAB,
            JAIL,
            KOREAT,
            LACT,
            LAGO,
            LDAM,
            LEGSQU,
            LMESA,
            LOSPUER,
            MIRR,
            MORN,
            MOVIE,
            MTCHIL,
            MTGORDO,
            MTJOSE,
            MURRI,
            NCHU,
            NOOSE,
            OCEANA,
            PALCOV,
            PALETO,
            PALFOR,
            PALHIGH,
            PALMPOW,
            PBLUFF,
            PBOX,
            PROCOB,
            RANCHO,
            RGLEN,
            RICHM,
            ROCKF,
            RTRAK,
            SANAND,
            SANCHIA,
            SANDY,
            SKID,
            SLAB,
            STAD,
            STRAW,
            TATAMO,
            TERMINA,
            TEXTI,
            TONGVAH,
            TONGVAV,
            VCANA,
            VESP,
            VINE,
            WINDF,
            WVINE,
            ZANCUDO,
            ZP_ORT,
            ZQ_UAR,
        };

        //public enum EZones
        //{
        //    Los_Santos_International_Airport,
        //    Alamo_Sea,
        //    Alta,
        //    Fort_Zancudo,
        //    Banham_Canyon_Dr,
        //    Banning,
        //    Vespucci_Beach,
        //    Banham_Canyon,
        //    Braddock_Pass,
        //    Braddock_Tunnel,
        //    Burton,
        //    Calafia_Bridge,
        //    Raton_Canyon,
        //    Cassidy_Creek,
        //    Chamberlain_Hills,
        //    Vinewood_Hills,
        //    Chumash,
        //    Chiliad_Mountain_State_Wilderness,
        //    Cypress_Flats,
        //    Davis,
        //    Del_Perro_Beach,
        //    Del_Perro,
        //    La_Puerta,
        //    Grand_Senora_Desert,
        //    Downtown,
        //    Downtown_Vinewood,
        //    East_Vinewood,
        //    El_Burro_Heights,
        //    El_Gordo_Lighthouse,
        //    Elysian_Island,
        //    Galilee,
        //    GWC_and_Golfing_Society,
        //    Grapeseed,
        //    Great_Chaparral,
        //    Harmony,
        //    Hawick,
        //    Vinewood_Racetrack,
        //    Humane_Labs_and_Research,
        //    Bolingbroke_Penitentiary,
        //    Little_Seoul,
        //    Land_Act_Reservoir,
        //    Lago_Zancudo,
        //    Land_Act_Dam,
        //    Legion_Square,
        //    La_Mesa,
        //    La_Puerta,
        //    Mirror_Park,
        //    Morningwood,
        //    Richards_Majestic,
        //    Mount_Chiliad,
        //    Mount_Gordo,
        //    Mount_Josiah,
        //    Murrieta_Heights,
        //    North_Chumash,
        //    N.O.O.S.E,
        //    Pacific_Ocean,
        //    Paleto_Cove,
        //    Paleto_Bay,
        //    Paleto_Forest,
        //    Palomino_Highlands,
        //    Palmer_-_Taylor_Power_Station,
        //    Pacific_Bluffs,
        //    Pillbox_Hill,
        //    Procopio_Beach,
        //    Rancho,
        //    Richman_Glen,
        //    Richman,
        //    Rockford_Hills,
        //    Redwood_Lights_Track,
        //    San_Andreas,
        //    San_Chianski_Mountain_Range,
        //    Sandy_Shores,
        //    Mission_Row,
        //    Stab_City,
        //    Maze_Bank_Arena,
        //    Strawberry,
        //    Tataviam_Mountains,
        //    Terminal,
        //    Textile_City,
        //    Tongva_Hills,
        //    Tongva_Valley,
        //    Vespucci_Canals,
        //    Vespucci,
        //    Vinewood,
        //    Ron_Alternates_Wind_Farm,
        //    West_Vinewood,
        //    Zancudo_River,
        //    Port_of_South_Los_Santos,
        //    Davis_Quartz,
        //};

        public static readonly Dictionary<string, string> ZoneNames = new Dictionary<string, string>
        {
            {"AIRP", "Los Santos International Airport"},
            {"ALAMO", "Alamo Sea"},
            {"ALTA", "Alta"},
            {"ARMYB", "Fort Zancudo"},
            {"BANHAMC", "Banham Canyon Dr"},
            {"BANNING", "Banning"},
            {"BEACH", "Vespucci Beach"},
            {"BHAMCA", "Banham Canyon"},
            {"BRADP", "Braddock Pass"},
            {"BRADT", "Braddock Tunnel"},
            {"BURTON", "Burton"},
            {"CALAFB", "Calafia Bridge"},
            {"CANNY", "Raton Canyon"},
            {"CCREAK", "Cassidy Creek"},
            {"CHAMH", "Chamberlain Hills"},
            {"CHIL", "Vinewood Hills"},
            {"CHU", "Chumash"},
            {"CMSW", "Chiliad Mountain State Wilderness"},
            {"CYPRE", "Cypress Flats"},
            {"DAVIS", "Davis"},
            {"DELBE", "Del Perro Beach"},
            {"DELPE", "Del Perro"},
            {"DELSOL", "La Puerta"},
            {"DESRT", "Grand Senora Desert"},
            {"DOWNT", "Downtown"},
            {"DTVINE", "Downtown Vinewood"},
            {"EAST_V", "East Vinewood"},
            {"EBURO", "El Burro Heights"},
            {"ELGORL", "El Gordo Lighthouse"},
            {"ELYSIAN", "Elysian Island"},
            {"GALFISH", "Galilee"},
            {"GOLF", "GWC and Golfing Society"},
            {"GRAPES", "Grapeseed"},
            {"GREATC", "Great Chaparral"},
            {"HARMO", "Harmony"},
            {"HAWICK", "Hawick"},
            {"HORS", "Vinewood Racetrack"},
            {"HUMLAB", "Humane Labs and Research"},
            {"JAIL", "Bolingbroke Penitentiary"},
            {"KOREAT", "Little Seoul"},
            {"LACT", "Land Act Reservoir"},
            {"LAGO", "Lago Zancudo"},
            {"LDAM", "Land Act Dam"},
            {"LEGSQU", "Legion Square"},
            {"LMESA", "La Mesa"},
            {"LOSPUER", "La Puerta"},
            {"MIRR", "Mirror Park"},
            {"MORN", "Morningwood"},
            {"MOVIE", "Richards Majestic"},
            {"MTCHIL", "Mount Chiliad"},
            {"MTGORDO", "Mount Gordo"},
            {"MTJOSE", "Mount Josiah"},
            {"MURRI", "Murrieta Heights"},
            {"NCHU", "North Chumash"},
            {"NOOSE", "N.O.O.S.E"},
            {"OCEANA", "Pacific Ocean"},
            {"PALCOV", "Paleto Cove"},
            {"PALETO", "Paleto Bay"},
            {"PALFOR", "Paleto Forest"},
            {"PALHIGH", "Palomino Highlands"},
            {"PALMPOW", "Palmer - Taylor Power Station"},
            {"PBLUFF", "Pacific Bluffs"},
            {"PBOX", "Pillbox Hill"},
            {"PROCOB", "Procopio Beach"},
            {"RANCHO", "Rancho"},
            {"RGLEN", "Richman Glen"},
            {"RICHM", "Richman"},
            {"ROCKF", "Rockford Hills"},
            {"RTRAK", "Redwood Lights Track"},
            {"SANAND", "San Andreas"},
            {"SANCHIA", "San Chianski Mountain Range"},
            {"SANDY", "Sandy Shores"},
            {"SKID", "Mission Row"},
            {"SLAB", "Stab City"},
            {"STAD", "Maze Bank Arena"},
            {"STRAW", "Strawberry"},
            {"TATAMO", "Tataviam Mountains"},
            {"TERMINA", "Terminal"},
            {"TEXTI", "Textile City"},
            {"TONGVAH", "Tongva Hills"},
            {"TONGVAV", "Tongva Valley"},
            {"VCANA", "Vespucci Canals"},
            {"VESP", "Vespucci"},
            {"VINE", "Vinewood"},
            {"WINDF", "Ron Alternates Wind Farm"},
            {"WVINE", "West Vinewood"},
            {"ZANCUDO", "Zancudo River"},
            {"ZP_ORT", "Port of South Los Santos"},
            {"ZQ_UAR", "Davis Quartz"},
        };
    }
}
